/** Declaration file generated by dts-gen */

export = site_config

declare const site_config: {
  author?: string
  authorBio?: string
  authorImage?: string
  brandColor?: string
  description?: string
  logo: string
  company: string
  siteUrl: string
  social: {
    github: string
    reddit: string
    twitter: string
    discord: string
    medium: string
  }
  meta: {
    banner: string
    title: string
    description: string
    language: string
  }
  intergrations: {
    facebookId: string
    googleAnalyticsTrackingId: string
    googleTagManager: string
  }
  theme?: string
  title?: string
}
